version: '3.3'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: akhuphusingshekali
      MYSQL_DATABASE: db_store
    ports:
      - '3308:3306'
    expose:
      - "3308"
    volumes:
      - ./mysql-dump/:/docker-entrypoint-initdb.d/
    networks:
      - poc-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    depends_on:
      - mysql
    networks:
      - poc-network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAEGER_AGENT_HOST: jaeger
      JAEGER_SERVICE_NAME: poc
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    ports:
      - "9999:9999"
    expose:
      - "9999"
    command: "http-start"
    restart: always
    depends_on:
      - mysql
      - jaeger
    links:
      - mysql
      - jaeger
    volumes:
      - app:/var/go
    networks:
      - poc-network

volumes:
  cache:
  app:

networks:
  poc-network:
    driver: bridge